siteName: Alaska Sailing Club
menus:
  primary:
    - label: Home
      url: /
    - label: Education
      url: /education/
    - label: Racing
      url: /racing/
    - label: Events
      url: /events/
    - label: Join
      url: /join/
    - label: Members
      url: /members/
      children:
        - label: New Member Guide
          url: /new-member-guide/
        - label: My Account
          url: /my-account/
        - label: Member Directory
          url: /directory/
        - label: Visiting the Club
          url: /visiting-the-club/
        - label: Issues & Support
          url: /issues-and-support/
        - label: Get Involved
          url: /get-involved/
        - label: Discord Server
          url: /discord-server/
    - label: Contact
      url: /contact/
vocabulary:
  - value: news
    label: News
  - value: racing
    label: Racing
  - value: results
    label: Results
  - value: education
    label: Education
  - value: club
    label: Club
spellcheck:
  dialect: en-US
